#!/usr/bin/env python3
"""Create anonymized, deterministic submission artifacts."""

from __future__ import annotations

import hashlib
import shutil
import subprocess
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "submission"
FIXED_TIME = (2026, 7, 26, 0, 0, 0)

INCLUDE_FILES = (
    "README.md",
    "Makefile",
    "requirements.txt",
    "pyproject.toml",
    "LICENSE",
    "results/RESULTS_SUMMARY.md",
    "paper/main.tex",
    "paper/supplement.tex",
    "paper/references.bib",
    "paper/ReproducibilityChecklist.tex",
    "paper/aaai27draft.sty",
    "AAAI_AuthorKit27/aaai2027.sty",
    "AAAI_AuthorKit27/aaai2027.bst",
)
INCLUDE_DIRS = (
    "src",
    "experiments",
    "tests",
    "scripts",
    "results/data",
    "results/figures",
    "paper/sections",
    "paper/supp_sections",
)
TEXT_SUFFIXES = {
    ".bib",
    ".json",
    ".md",
    ".py",
    ".sty",
    ".tex",
    ".txt",
    ".yml",
    ".yaml",
    ".toml",
    ".csv",
}
FORBIDDEN_IDENTIFIERS = (
    "jing" + "xuxie",
    "eston" + " javas",
    "@berkeley" + ".edu",
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def include_file(path: Path) -> bool:
    if path.is_dir():
        return False
    if "__pycache__" in path.parts:
        return False
    if path.suffix in {".pyc", ".pyo"}:
        return False
    return True


def collect_entries() -> list[Path]:
    entries: list[Path] = [ROOT / name for name in INCLUDE_FILES]
    for directory in INCLUDE_DIRS:
        entries.extend(path for path in (ROOT / directory).rglob("*") if include_file(path))
    entries = sorted(set(entries), key=lambda path: path.relative_to(ROOT).as_posix())
    missing = [path for path in entries if not path.exists()]
    if missing:
        joined = ", ".join(str(path.relative_to(ROOT)) for path in missing)
        raise RuntimeError(f"missing package inputs: {joined}")
    return entries


def scan_text(label: str, text: str) -> None:
    lower = text.lower()
    for marker in FORBIDDEN_IDENTIFIERS:
        if marker in lower:
            raise RuntimeError(f"author identifier {marker!r} found in {label}")


def scan_anonymity(entries: list[Path], pdfs: tuple[Path, ...]) -> None:
    for path in entries:
        if path.suffix.lower() in TEXT_SUFFIXES or path.name in {"Makefile", "LICENSE"}:
            scan_text(str(path.relative_to(ROOT)), path.read_text(encoding="utf-8", errors="replace"))
    for path in pdfs:
        completed = subprocess.run(
            ["pdftotext", str(path), "-"],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        scan_text(path.name, completed.stdout)


def write_zip(destination: Path, entries: list[Path]) -> None:
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in entries:
            relative = path.relative_to(ROOT).as_posix()
            info = zipfile.ZipInfo(relative, FIXED_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, path.read_bytes())


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    main_pdf = OUT / "contrastive-coverage-main.pdf"
    supplement_pdf = OUT / "contrastive-coverage-supplement.pdf"
    code_zip = OUT / "contrastive-coverage-code-and-data.zip"
    shutil.copy2(ROOT / "paper" / "main.pdf", main_pdf)
    shutil.copy2(ROOT / "paper" / "supplement.pdf", supplement_pdf)

    entries = collect_entries()
    scan_anonymity(entries, (main_pdf, supplement_pdf))
    write_zip(code_zip, entries)

    artifacts = (main_pdf, supplement_pdf, code_zip)
    manifest = [
        "Contrastive Coverage submission artifacts",
        "Generated by: make submission-bundle",
        "The ZIP contains no .git metadata or detected author identifiers.",
        "",
    ]
    for artifact in artifacts:
        manifest.append(f"{sha256(artifact)}  {artifact.name}")
    (OUT / "MANIFEST.txt").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print("\n".join(manifest))


if __name__ == "__main__":
    main()
